name: PR-check Pipeline

on:
  pull_request:
    branches: [main]  # Запускать только при PR в ветку main
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest  # Используем GitHub-hosted runner с Ubuntu

    steps:
      - uses: actions/checkout@v3  # Клонирует код из репозитория

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test